### ISSUE TITLE
How to get Gateway latency?

### ISSUE THREAD

**Issue by trbodev** [shardlab/discordcr#26]

**Comment by PixeLInc** [comment]
We do not have anything that would give you that.

You can track these values by yourself to a degree, for example, in discord.py they measure HEARTBEAT -> HEARTBEAT_ACK.
To do this you can hook on to the `on_dispatch` event with the client and listen for those events, and set/measure accordingly.

**Comment by trbodev** [comment]
Looking through the code `on_dispatch` would never receive `HEARTBEAT` and `HEARTBEAT_ACK` because they are OP codes and not dispatch events.

**Comment by PixeLInc** [comment]
Ah yes, woops.

In this case, we do not support doing that.

I think maybe the most useful thing we could do is add an `on_raw` event which dispatches the raw packet we receive.
I can do this at some point, or feel free to make a PR adding this. should be like a few line change.

**Comment by storm37000** [comment]
Discord.Net has a `LatencyUpdated` event that passes in the previous and new latency.

**Comment by PixeLInc** [comment]
Indeed, but that is a more high-level library while this library is low-level, 1:1 with the API.
I am closing this issue since it has been answered already and another issue with a more general feature request was made.
