### ISSUE TITLE
Is there a discord server for discordcr?

### ISSUE THREAD

**Issue by Lunari8546** [shardlab/discordcr#34]
Title.

**Comment by PixeLInc** [comment]
We mainly use the #crystal_discordcr channel in the Discord API server (https://discord.gg/discord-api)
other than that, we have a private server for our organization called ShardLab (https://discord.gg/qspgyK6FyS)

either works, but the dapi one has 'more' people.

**Comment by Lunari8546** [comment]
Thank you for your fast reply.
