### ISSUE TITLE
Support Message Allowed Mentions

### ISSUE THREAD

**Issue by Daniel-Worrall** [shardlab/discordcr#5]
If allowed mentions aren't passed by the library, it is taken from context. Passing a custom allowed mention object is useful for parsing and returning user-provided messages to not accidentally ping or even use as a logger so that events can be logged with a mention to the user without that user being bombarded with mentions.
https://discord.com/developers/docs/resources/channel#allowed-mentions-object

Oops, closed by #4

**Comment by PixeLInc** [comment]
Closed in #30
